In [2]:
import random

n = 4
N = 2**n
N2 = 2*N
q = 65537

R1.<x> = PolynomialRing(Zmod(q))
R1 = R1.quo(x^N + 1)

def automorphism(poly, k):
    ans = [0] * N
    for i in range(N):
        if (i*k) % N2 < N:
            ans[(i*k) % N2] = poly[i]
        else:
            ans[(i*k) % N2 - N] = -poly[i]
    return R1(ans)

poly1 = R1([i for i in range(N)])
poly1 = R1(random.randint(0, q-1))
# poly1 = R1.random_element()
# poly1 = R1([1])
print(poly1)
# print(automorphism(poly1, 3))
acc = 0
for i in range(N):
    acc += automorphism(poly1, 2*i + 1)
    # print(2*i + 1)
print(acc/N)

14745
14745


In [52]:
import numpy as np
n=4
N = 2**n
N2 = 2*N
def count_nonzero_diagonals(matrix: np.ndarray) -> int:  
    n = matrix.shape[0]  
    count = 0 
    for k in range(-(n-1), n):
        diagonal_elements = np.diag(matrix, k=k)
        if np.any(diagonal_elements != 0):
            count += 1
    print("对角线条数：",count)
    return count

def create_diag_matrix(n, step):
    N = 2**n
    matrix = np.zeros((N, N), dtype=int) 
    offset = 2**(n-step)
    
    #主对角线
    for i in range(N):
        if((i & (1 << (step - 1))) == 0) :        
            matrix[i, i] = 1  
        else:
            if((i & offset) != 0):
                matrix[i, i - offset] = 1 
            else:
                matrix[i, i + offset] = 1

    # print(matrix)
    return matrix

def get_bit(n):
    return len(bin(n-1))-2

def get_rev(n):
    rev = []
    for i in range(n):
        rev.append(int((bin(i)[:1:-1]+(get_bit(n)-len(bin(i)[:1:-1]))*'0'),2))
    return rev

matrix = np.zeros((N), dtype=int) 
for i in range(N):
    matrix[i] = i

# def change_diag(diag, tag = 0):
#     for i in range(len(diag)):
#         if diag[i] == 1:
#             tag = tag + 1
#             if tag % 2 == 1:
#                 diag[i] = -1
#     return diag
m_list = [create_diag_matrix(n, step) for step in range(1, n+1)]
for m in m_list:
    for i in range(N):
        for j in range(N):
            if i + j < N:
                # m[i][j] = -m[i][j]
                pass
# for idx in range(n):
    # m = m_list[idx]
    # diag = change_diag(list(np.diag(m, k = 0)), 1)
    # for i in range(len(diag)):
    #     m[i][i] = diag[i]
    # diag = change_diag(list(np.diag(m, k = 2**(n - idx - 1))), 1)
    # for i in range(len(diag)):
    #     m[i][i + 2**(n - idx - 1)] = diag[i]
    # diag = change_diag(list(np.diag(m, k = -2**(n - idx - 1))), 1)
    # for i in range(len(diag)):
    #     m[i + 2**(n - idx - 1)][i] = diag[i]
# n为奇数时 矩阵m_((n+1)/2)无意义：m4 = create_diag_matrix(n,4)
rev = get_rev(N)
print("rev:", rev)
output = matrix
for current_matrix in range(n):
    if current_matrix == (n - 1) // 2 and n % 2 == 1:
        continue
    print(current_matrix)
    output = output @ m_list[current_matrix]
    # print(output)
if n % 2 == 1:
    start = int((n - 1)/2)
else:
    start = int(n / 2)
for i in range(start):
    print(start - i - 1)
    output = output @ m_list[start - i - 1]
    # print(output)
print(abs(output) == rev)

tmp = np.zeros((N, N), dtype=int)
for current_matrix in range(n):
    if current_matrix == 0:
        tmp += m_list[0]
    elif current_matrix == (n - 1) // 2 and n % 2 == 1:
        continue
    else:
        tmp = tmp @ m_list[current_matrix]
for i in range(start):
    tmp = tmp @ m_list[start - i - 1]
count_nonzero_diagonals(tmp)
count_nonzero_diagonals(m_list[1]@m_list[0])
print(tmp.shape)
# print(matrix @ tmp)
# print((matrix @ tmp) == rev)


rev: [0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15]
0
1
2
3
1
0
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
对角线条数： 9
对角线条数： 7
(16, 16)


In [4]:
current_matrix = 3
mat = m_list[current_matrix]
print(mat)
for k in range(N):
    diagk = [0] * N
    for i in range(N):
        for j in range(N):
            idx = (i-(2*k+1)*j) % N2
            if idx >= N:
                diagk[idx - N] -= mat[i][j]
            else:
                diagk[idx] += mat[i][j]
    # print(diagk)
    if diagk != [0]*N:
        print("zero diag:", k, diagk)


[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
zero diag: 0 [8, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -4]
zero diag: 1 [1, 0, -1, 0, -1, 2, -1, 0, -1, 2, -1, 0, -1, 2, -1, 0]
zero diag: 3 [1, -2, 1, 0, -1, 2, -1, 0, 1, 0, -1, 0, -1, 0, 1, 0]
zero diag: 5 [1, -2, 1, 0, 1, 0, -1, 0, -1, 2, -1, 0, 1, -2, 1, 0]
zero diag: 7 [1, 0, -1, 0, 1, 0, -1, 0, 1, 0, -1, 0, 1, 0, -1, 0]
zero diag: 8 [0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4]
zero diag: 9 [1, -2, 1, 0, -1, 0, 1, 0, -1, 0

In [5]:
poly_vec = [0] * N

for k in range(N):
    diagk = [0] * N
    for i in range(N):
        j = rev[i]
        idx = (i-(2*k+1)*j) % N2
        if idx >= N:
            diagk[idx - N] -= 1
        else:
            diagk[idx] += 1
    poly_vec[k] = R1(diagk)

random_poly = R1.random_element()
print(random_poly)
acc = 0
for k in range(N):
    acc += poly_vec[k] * automorphism(random_poly, 2*k + 1)
    print(2*k + 1)
print(acc / N)

57009*xbar^15 + 12280*xbar^14 + 9457*xbar^13 + 13944*xbar^12 + 63874*xbar^11 + 20187*xbar^10 + 992*xbar^9 + 49312*xbar^8 + 5977*xbar^7 + 6874*xbar^6 + 37884*xbar^5 + 3323*xbar^4 + 58718*xbar^3 + 19138*xbar^2 + 37030*xbar + 9818
1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
57009*xbar^15 + 5977*xbar^14 + 63874*xbar^13 + 58718*xbar^12 + 9457*xbar^11 + 37884*xbar^10 + 992*xbar^9 + 37030*xbar^8 + 12280*xbar^7 + 6874*xbar^6 + 20187*xbar^5 + 19138*xbar^4 + 13944*xbar^3 + 3323*xbar^2 + 49312*xbar + 9818


In [6]:
from scipy.fft import fft, ifft
import numpy as np
# Create a sample signal
diag = np.diag(m_list[1], 4)
diag = list(diag) + [0]*4
print(diag)
x = np.array(diag)
# Compute the FFT
y = ifft(x)
for i in range(N):
    y[i] = y[rev[i]]
z = fft(y)
print(z)
for i in range(N):
    z[i] = z[rev[i]]
print(z)
# Compute the inverse FFT
# yinv = fft(y)
# print(yinv)

[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[-0.16161165-0.39016504j -0.19751553+0.08523105j  0.83838835-0.14016504j
  0.75859031+0.33281456j  0.16161165+0.03661165j -0.22479607+0.28103786j
  0.58838835+0.31694174j  0.28103786-0.42848541j  0.08838835-0.28661165j
 -0.33281456-0.51200774j  0.48483496+0.21338835j  0.814633  +0.19751553j
 -0.08838835+0.64016504j  0.75512615+0.14573884j  0.08838835-0.39016504j
  0.14573884-0.10184467j]
[-0.16161165-0.39016504j  0.08838835-0.28661165j  0.16161165+0.03661165j
 -0.08838835+0.64016504j  0.16161165+0.03661165j  0.48483496+0.21338835j
  0.58838835+0.31694174j  0.08838835-0.39016504j  0.08838835-0.28661165j
 -0.33281456-0.51200774j  0.48483496+0.21338835j  0.75512615+0.14573884j
 -0.08838835+0.64016504j  0.75512615+0.14573884j  0.08838835-0.39016504j
  0.14573884-0.10184467j]
