In [ ]:
# 256*128*256列主
import numpy as np

n = 4
# matrix_C = matrix_A * matrix_B
data_a = np.random.randint(-5, 5, size=(16, ), dtype=int)
# print(data_a)
data_b = np.random.randint(-5, 5, size=(16, ), dtype=int)
matrix_A = data_a.reshape(4, 4)
matrix_B = data_b.reshape(4, 4)

print(matrix_A)
print(matrix_B)

[[ 4 -4  2 -3]
 [ 2  1 -3 -2]
 [ 2  0  3 -4]
 [ 0  4  2  0]]
[[-2  3 -4  2]
 [ 3  2 -1 -1]
 [-2 -3  1  0]
 [ 2  2 -4  2]]


In [10]:
def tweak1(mat):
    matrix_C = mat.copy()
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            matrix_C[i, j] = mat[i, (j+i) % mat.shape[1]]
    return matrix_C

def tweak1_inv(mat):
    matrix_C = mat.copy()
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            matrix_C[i, j] = mat[i, (j-i) % mat.shape[1]]
    return matrix_C

def tweak2(mat):
    matrix_C = mat.copy()
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            matrix_C[i, j] = mat[(j+i) % mat.shape[0], j]
    return matrix_C


# def tweak2_inv(mat):
#     matrix_C = mat.copy()
#     for i in range(mat.shape[0]):
#         for j in range(mat.shape[1]):
#             matrix_C[i, j] = mat[(i-j) % mat.shape[0], j]
#     return matrix_C

def tweak3(mat, k):
    matrix_C = mat.copy()
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            matrix_C[i, j] = mat[i, (j+k) % mat.shape[1]]
    return matrix_C

def tweak4(mat, k):
    matrix_C = mat.copy()
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            matrix_C[i, j] = mat[(i+k) % mat.shape[0], j]
    return matrix_C

# temp1 = tweak1(matrix_A)
# temp2 = tweak2(matrix_B)

# n = matrix_A.shape[0]
# d = matrix_A.shape[1]

# plain = np.zeros(16).reshape(4, 4)

# print(matrix_A @ matrix_B)
 
# for i in range(n):
#     plain += tweak3(temp1, i) * tweak4(temp2, i)
# print(plain)

In [13]:
# print(matrix_A)
# print(matrix_B)

mask1 = np.array([1 if (i % n == 0) else 0 for i in range(n*n)]).reshape(n, n)
mask2 = np.array([1 if (i % n == 1) else 0 for i in range(n*n)]).reshape(n, n)
mask3 = np.array([1 if (i % n == 2) else 0 for i in range(n*n)]).reshape(n, n)
mask4 = np.array([1 if (i % n == 3) else 0 for i in range(n*n)]).reshape(n, n)

def rot_left(mat, k):
    return tweak3(mat, k)
def rot_up(mat, k):
    return tweak4(mat, k)

rot_B = []
for i in range(n):
    temp = np.zeros(n*n).reshape(n, n)
    for j in range(n):
        temp[j] = matrix_B[(j+i)%n]
    rot_B.append(matrix_A * temp)

# phase 1
rot_B[0] += rot_left(rot_B[0], 2)
rot_B[0] = rot_B[0] * (mask1 + mask2)
# print(rot_B[0])

# print(rot_B[1])
rot_B[1] += rot_left(rot_B[1], 2)
rot_B[1] *= (mask1 + mask2)
# print(rot_B[1])

# print(rot_B[2])
rot_B[2] += rot_left(rot_B[2], -2)
rot_B[2] *= (mask3 + mask4)
# print(rot_B[2])


rot_B[3] += rot_left(rot_B[3], -2)
rot_B[3] *= (mask3 + mask4)

rot_B[0] += rot_B[2]
# print(rot_B[0])
rot_B[1] += rot_B[3]


rot_B[0] += rot_left(rot_B[0], 1)
rot_B[0] *= (mask1 + mask3)

rot_B[1] += rot_left(rot_B[1], -1)
rot_B[1] *= (mask2 + mask4)


# print(tweak1(tweak1_inv(rot_B[0])))


# mat_C = tweak1_inv(rot_B[0])
# mat_D = matrix_B.copy()


# # temp1 = tweak1(mat_C)
# temp1 = rot_B[0]
# temp2 = tweak2(mat_D)

# plain = np.zeros(16).reshape(4, 4)

# print(mat_C @ mat_D)
 
# for i in range(n):
#     plain += tweak3(temp1, i) * tweak4(temp2, i)
# print(plain)
rot_B[0] += rot_B[1]
print((rot_B[0]))
print(tweak1_inv(rot_B[0]))
print(matrix_A @ matrix_B.T)

[[-34.   5.   6. -14.]
 [ 13. -10.  14.   7.]
 [ -1. -16. -24.   7.]
 [  0.   4.   6. -10.]]
[[-34.   5.   6. -14.]
 [  7.  13. -10.  14.]
 [-24.   7.  -1. -16.]
 [  4.   6. -10.   0.]]
[[-34   5   6 -14]
 [  7  13 -10  14]
 [-24   7  -1 -16]
 [  4   6 -10   0]]
